---
permalink: pretty
markdown: kramdown
exclude:
  - Gem*
  - "*.lock"
  - "*rb"
  - ".git*"
  - "*.md"
  - "*.json"
  - node_modules
  - vendor
  - gulp*
  - ".jekyll-metadata"
  - ".*"
timezone: UTC
author: Nerdlab
title: "Traveljam"
description: "Plan the most personal citytrip of 2050. 26th April 2019: 9h to 22h, The Beacon Antwerp"
url: "https://traveljam.be"
navigation:
  - title: Assignment
    url: "index.html#opdracht"
  - title: Schedule
    url: "index.html#programma"
  - title: Coaches
    url: "index.html#coaches"
navigation-cta:
  - title: Pitches
    url: "pitches/"
social:
  twitter_username: traveljam_be
  instagram_username: traveljam_be
  facebook_link: https://www.facebook.com/events/381917469256458/
legal:
  year: '2019'
  company: 'Nerdlab vzw'
  email: 'info@nerdlab.be'
  address: 'Ma√Øsstraat 181'
  city: '9000 Ghent'
  phone: '+32 486 22 72 02'
  btw: 'BE 0562.981.862'
labels:
  legal: Fineprint
collections:
  pages:
    title: Pages
    output: true
defaults:
- scope:
    path: ""
    type: pages
  values:
    is_page: true
